
dashboard_layout:
  rows:
    - columns:
      - width: 12
        widgets:
          - welcome
      - width: 12
        widgets:
          - recently_used_apps

    - columns:
      - width: 8
        widgets:
          - motd
      - width: 4
        widgets:
          - xdmod_widget_job_efficiency
          - xdmod_widget_jobs

profiles:
  booth_research:
    brand_bg_color: '#800000'

    nav_bar:
      - files
      - clusters
      - title: 'Resources'
        links:
          - title: "Chicago Booth IT"
            icon: "fa://life-ring"
            url: "https://www.chicagobooth.edu/"
          - title: "Research Computing"
            icon: "fa://chart-bar"
            url: "https://www.chicagobooth.edu/"
      - my interactive sessions
      - title: 'Jupyter'
        icon: 'fa://star'
        links:
          - 'sys/jupyter'

      - title: "Research Notes"
        icon: "fa://book-open"
        page: "booth_research_notes"

    help_bar:
      - help

    dashboard_layout:
      rows:
        - columns:
          - width: 12
            widgets:
              - recently_used_apps

        - columns:
          - width: 8
            widgets:
              - booth_research_notes
          - width: 4
            widgets:
              - xdmod_widget_job_efficiency
              - xdmod_widget_jobs

        - columns:
          - width: 12
            widgets:
              - motd


profile_links:
  - group: "Profiles"
  - profile: ""
    title: "Default"
    icon:  "fas://user"
  - profile: booth_research
    icon: "fas://flask"
    title: "Research Computing"

custom_pages:
  booth_research_notes:
    rows:
      - columns:
        - width: 6
          widgets:
            - welcome
            - custom_page_description
        - width: 6
          widgets: booth_research_notes
